### ISSUE TITLE
Add Option To Sort Value Of className Attribute

### ISSUE THREAD

**Issue by lots0logs** [wildpeaks/package-snapshot-dom#34]
This would be useful when using snapshots for automated testing (obviously). I'll try and submit a PR soon.

**Comment by cecilemuller** [comment]
Thanks for the issue and PR 😃 

Ok, I'll turn the second parameter into an Object and add an option with the behavior of `sortAttrs`.

Checklist to track progress:
- [ ] I'll change the existing tests to expect an Object
- [ ] I'll mirror the changes to the "browser" version too
- [ ] I'll add tests for the new option
- [ ] it's an API change, so the release has to be a major number

**Comment by cecilemuller** [comment]
Hmm, the more I think about it, the more it seems out of scope to add this option because the only purpose of the package is to give an accurate view of the current state of the DOM.


So the better solution is to transform the resulting tree because you only need to sort class values, but someone else might need a completely different transformation (like parsing JSON stored in a data attribute, for example). Even something small like handling multiple consecutive whitespaces wouldn't be unanimous. If anything, I even regret adding the "skip empty values" option because that is a transformation too.

But I get it, it's easier on the short term to just pass an option to the parser and be done with it.


So what I'm going to do is:
 - remove the second parameter entirely
 - expose a function that can apply a "removes empty values" transformation
 - expose a function that can apply a "sort the value of specific attributes" transformation

It won't be a big change for existing users:
 - no change at all if they didn't use the "skip empty values" option
 - one function call after the snapshot if they used the option

That way if people need to sort differently, or need different transformations, they can write their own functions and use the two examples functions as base.

**Comment by lots0logs** [comment]
![good-plan](https://media.giphy.com/media/W4uHXlNXoRvlegeDO6/giphy.gif)

**Comment by cecilemuller** [comment]
The new version is published 🎉 
https://github.com/wildpeaks/package-snapshot-dom/tree/master/packages/snapshot-dom#sort-values
